### ISSUE TITLE
Support ABCD-A or DwC-A from BioCASe installation

### ISSUE THREAD

**Issue by timrobertson100** [gbif/crawler#11]
The PyWrapper software has supported DwC-A and ABCD-A since version 3.4.

An analysis in November 2017 showed the versions installed as:

Version | Number
-- | --
2.5.4 | 10
2.6.1 | 2
3.0 | 1
3.0RC2 | 1
3.2 | 1
3.3 | 1
3.3.1 | 2
3.4 | 2
3.4.1 | 1
3.5 | 1
3.5.1 | 1
3.5.2 | 1
3.5.3 | 3
3.6.0 | 4
3.6.1 | 1
3.6.2 | 1
3.6.3 | 11
3.6.4 | 5
(unknown) | 6

GBIF should support the archive view in crawling.  The PyWrapper can expose none, ABCD-A or ABCD-A and DwC-A.  A first step should be to determine which are actually available today to determine if using DwC-A exclusively is an option (since the PyWrapper has already done an extensive mapping with e.g. identification history extensions).

**Comment by timrobertson100** [comment]
There are 191 URLs to test
[biocase-urls.txt](https://github.com/gbif/crawler/files/1796974/biocase-urls.txt)

**Comment by timrobertson100** [comment]
Attached is a CSV of the 53 endpoints (56 GBIF datasets) that have archives

[archives.txt](https://github.com/gbif/crawler/files/1797248/archives.txt)

**Comment by MattBlissett** [comment]
Comments from Jörg:

> I've implemented an option in BioCASe to set an expiration period for archives at dataset level (defaults to 0, which means never). This allows curators to prevent outdated archives from being used. If set to let's say 180, for example, and the archives have not been updated (either manually or through a cron job) for the past 6 months, they will be dropped from the inventory - so any harvesting will have to use the BioCASe web service again, which always provides the up-to-date records.
>
> Which leads me to the question: Will the BioCASe inventory be queried in regular intervals? So... if the archives (both ABCD and DwC) disappear from the inventory, will  harvesting switch back to using the BioCASe web service?

The inventory isn't queried at regular intervals, so we need to be aware that, when using an archive, we may be missing more recent data. Even when the archive is old, it is not removed from the filesystem, so we will continue getting HTTP 200/304 for the old archive.

For @gbif/content: a Registry metasync of a BioCASe installation will add ABCD-A endpoints (which are ignored) and DWC-A endpoints (which will then be used). I did this for the BGBM BioCASe, but nothing else -- it needs the careful checking that datasets won't be created/deleted because of minor changes to titles, and given this info from Jörg, probably a check with the host on whether they keep their archives up-to-date.

**Comment by timrobertson100** [comment]
@MattBlissett - just to confirm, you are saying this will only apply for the BGBM installation because we have assurance from Jörg that he keeps them up to date?

Based on what Jörg outlines, and the fact that it is not really deployed widely, I suggest we don't roll out DwC-A support for other installations as it seems highly likely to result in loss of new data.  I had assumed this was an on-by-default option in BioCASe installations and always updated on a sensible interval (e.g. nightly).

**Comment by MattBlissett** [comment]
Jörg has confirmed that he is keeping some BGBM datasets up-to-date, he removed the archives from the ones he won't keep up-to-date and I resynchronized them.

How often do we metasync BioCASe anyway? If it's almost never, it's OK to leave the code as it is. The DWC-A endpoint can be deleted manually if it's a problem.

BioCASe is written in PHP, which tends not to be deployed as a daemon, but runs only in response to an HTTP request. That makes scheduled tasks more difficult than in a typical Java web application, since it must rely on a cronjob or similar.

**Comment by jholetschek** [comment]
Tim, Matt,

as Matt said, BioCASe only runs in response to HTTP requests, so scheduling isn't easy to implement - even though it can be easily done through cron jobs.

My view on this is that he DarwinCore archive feature will only be used by providers of huge dataets with millions of records that run into issues when harvested through the BioCASe endpoint. They will need to create the archives explicitly and hence should be aware of the need to update (or else I will tell them). So I don't think this will be an issue - but I will keep an eye on that!

**Comment by MattBlissett** [comment]
We implemented this a couple of years ago.
