### ISSUE TITLE
Investigate Error communicating with ZooKeeper, getting status for ...

### ISSUE THREAD

**Issue by cgendreau** [gbif/crawler#2]
crawler-ws logs a lot of exceptions like:

```
org.gbif.api.exception.ServiceUnavailableException: Error communicating with ZooKeeper, getting status for 8d431c96-9e2f-4249-8b0a-d875e3273908
at org.gbif.crawler.DatasetProcessServiceImpl.getDatasetProcessStatus(DatasetProcessServiceImpl.java:180)
```

**Comment by cgendreau** [comment]
Debug information:
The error is thrown from `DatasetProcessServiceImpl` `getDatasetProcessStatus` function when `crawlPath` exists in ZooKeeper but contains nothing. We call `readValue` on the  `ObjectMapper` with that content (nothing) to transform it into a `CrawlJob` which will throw an exception.

**Comment by MattBlissett** [comment]
I have some mitigation in place for this, to clear out bad data every 20 minutes, but in periods <20 minutes it can mean crawl requests are denied with a log message "Requested crawl for dataset [11f7be1d-fdf3-4753-bfb0-c61ddbde3303] but crawl already scheduled or running, ignoring", even though the dataset won't show up on the [monitor](https://management-tools.gbif.org/crawling-monitor)

**Comment by MattBlissett** [comment]
I'm close to the cause of this.

When crawler-coordinator-cleanup runs `curator.delete().deletingChildrenIfNeeded().forPath(CrawlerNodePaths.getCrawlInfoPath(status.getDatasetKey()));`, we get errors in the ZooKeeper log (on the ZK servers) like `Error:KeeperErrorCode = Directory not empty for /uat_crawler/crawls/d4d77b21-464f-4e05-91ba-f6ebab042655`.

That appears to be caused by crawler-ws, which is often running `getDatasetProcessStatus(...)`.

My guess at the moment is that crawler-ws is recreating deleted nodes.

TBC.
